---
  - name: copy Docker Compose files
    copy:
      src: "docker-compose-db.yml"
      dest: ~/docker-compose.yml
  - name: Run container  
    become: true
    shell:
      cmd: "docker-compose -f docker-compose.yml up -d"   
