---
- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: yes

- name: Install Nginx
  apt:
    name: nginx
    state: latest

- name: unlink default  
  become: true
  ignore_errors: yes
  shell:
      cmd: "unlink /etc/nginx/sites-enabled/default"   

- name: Create reverse-proxy 
  template:
    src: "reverse-proxy.j2"
    dest: /etc/nginx/sites-available/reverse-proxy
    mode: 0644


- name: Enable config Nginx
  file:
    src: /etc/nginx/sites-available/reverse-proxy
    path: /etc/nginx/sites-enabled/reverse-proxy
    state: link

- name: Restart Nginx
  service:
    name: nginx
    state: restarted


