---
- hosts: another_ssh_servers
  become: true
  roles:
    - deploy_bastion

- hosts: docker_servers
  become: true
  roles:
    - deploy_docker

- hosts: db_servers
  roles:
    - deploy_db

- hosts: business_servers
  roles:    
    - deploy_business
    
- hosts: front_servers
  become: true
  roles:    
    - deploy_front

